config/routes.rb
Rails.application.routes.draw do
  root "chydak#Vtapke"
  get 'chydak/Vtapke'
  get "/chydak", to: "chydak#Vtapke"

  resources :chydak do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chydak.rb
class Chydak < ApplicationRecord

include Visible

    validates :title, presence: true
    has_many :comments, dependent: :destroy
    validates :body, presence: true, length: { minimum: 10 }

end

app/models/comment.rb
class Comment < ApplicationRecord
  
  include Visible
  
  belongs_to :chydak
  belongs_to :Vtapke
  
end

app/models/visible.rb
module Visible
    extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
        where(status:
        'public').count
    end
end

    def archived?
      status == 'archived'
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chydak_controller.rb
class ChydakController < ApplicationController

  http_basic_authenticate_with name: "dhh", 
  password: "secret", except: [:index, :show]

  def Vtapke
    @chydak=Chydak.all
  end
     
  def show
    @chydak = Chydak.find(params[:id])
  end

  def new
    @chydak = Chydak.new
  end

  def create
    @chydak = Chydak.new(chydak_params)

    if @chydak.save
      redirect_to @chydak
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @chydak=Chydak.find(params[:id])
  end

  def update
    @chydak=Chydak.find(params[:id])

    if @chydak.update(chydak_params)
      redirect_to @chydak
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @chydak=Chydak.find(params[:id])
    @chydak.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def chydak_params
    params.require(:chydak).permit(:title, :body, :status)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "dhh", 
  password: "secret", only: :destroy

  def create
    @chydak = Chydak.find(params[:chydak_id])
    @comment = @chydak.comments.create(comment_params)
        redicred_to chydak_path(@chydak)
  end

  def destroy
    @chydak = Chydak.find(params[:chydak_id])
    @comment = @chydak.comments.find(params[:id])
    @comment.destroy
    redirect_to chydak_path(@chydak), status: :see_other
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chydak_helper.rb
module ChydakHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/chydak/Chydak.html.erb
<h1>Chydak</h1>

Our SaPer has <%=Chydak.public_count %> chydak and counting!

<ul>
  <% @chydak.each do |chydak| %>
    <% unless chydak.archived? %>
    <li>
      <%= link_to chydak.title, chydak %>
    </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "New Chydilo", new_chydak_path %>

app/views/chydak/NewTapki.html.erb
<h1>New Chydak</h1>

<%= render "form", chydak: @chydak %>

<%= form_with model: @chydak do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
      <% @chydak.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
      <% @chydak.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chydak/Show.html.erb
<h1> <%= @chydak.title %> </h1>

<p> <%= @chydak.body %> </p>

<ul>
    <li><%= link_to "Edit", edit_chydak_path(@chydak)%></li>
    <li><%= link_to "Destroy", chydak_path(@chydak),
    
    data:{
            turbo_metod: :delate,
            turbo_confirm: "Are you sure?"
        }%></li>
</ul>

<h2>Comments</h2>
<% @chydak.comments.each do |comment|%>
    <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
    </p>

    <p>
    <strong>Comment:</strong>
    <%= comment.body %>
    </p>
    <% end %>

<h2>Add a comment</h2>
<%= from_with model: [@chydak, @chydak.comments.build] do |form| %>

<p>
<%= form.label :commenter %><br>
<%= form.text_field :commenter %>
</p>

<p>
<%= form.label :body %><br>
<%= form.text_field :body %>
</p>

<p>
<%= form.submit %>
</p>
<% end %>

app/views/chydak/Vtapke.html.erb
<h1>ChydakVtapke</h1>

<ul>
  <% @chydak.each do |chydak| %>
    <li>
      <a href="/chydak/<%= chydak.id %>">
        <%= chydak.title %>
      </a>
    </li>
  <% end %>
</ul>

app/views/chydak/_form.html.erb
<h1>FormChydak</h1>

<%= form_for(chydak, as: chydak, url: chydak_path(chydak), html: { data: { turbo: false} } ) do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
      <% chydak.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
      <% chydak.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], 
  selected: 'public' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chydak/edit.html.erb
<h1>EditChydak</h1>

<%= render "form", chydak: @chydak %>

app/views/chydak/form.html.erb
<h1>FormChydak</h1>

<%= form_with model: chydak do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
      <% chydak.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
      <% chydak.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chydak/new.html.erb
<h1>NewChydak</h1>

<%= render "form", chydak: @chydak %>

app/views/chydak/show.html.erb
<h1><%= @chydak.title %></h1>

<p><%= @chydak.body %></p>

<ul>
    <li><%= link_to "Edit", edit_chydak_path(@chydak) %></li>
    <li><%= link_to "Destroy", chydak_path(@chydak), data: {
            turbo_metod: :delate,
            turbo_confirm: "Are you sure?"
        } %></li>
</ul>

<h2>Comments</h2>
<% render @chydak.comments %>
    
<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
    <%= link_to "Destroy Comment", [comment.chydak, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @chydak, @chydak.comments.build ] do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
    <p>
      <%= form.label :status %><br>
      <%= form.select :status, ['public', 'private', 'archived'], 
    selected: 'public' %>
    </p>
    
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaPer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>